/**
 * Local-disk storage driver (AD-7) - development only.
 *
 * Same interface as ./s3.js so nothing above the driver changes, and no
 * `if (isDev)` branch leaks into the storage logic.
 *
 * Its "presigned URL" is a signed, expiring token pointing at a local route,
 * so the ACCESS PATTERN matches production: the caller still receives a
 * short-lived URL rather than a raw path. A developer therefore exercises the
 * same flow the deployed app uses, and a bug in that flow shows up locally.
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';

const ROOT = process.env.STORAGE_LOCAL_PATH || './uploads';

/**
 * Signing key for local URLs. Ephemeral by design: restarting the dev server
 * invalidates outstanding links, which is fine and mirrors expiry.
 */
const LOCAL_URL_SECRET = crypto.randomBytes(32);

const resolve = (key) => {
  const full = path.resolve(ROOT, key);
  const root = path.resolve(ROOT);
  // A key is generated by buildStorageKey and never user-supplied, but a
  // traversal here would escape the upload root entirely, so it is checked.
  if (!full.startsWith(root + path.sep) && full !== root) {
    throw new Error('storage: refusing to resolve a key outside the storage root');
  }
  return full;
};

export function createLocalDriver() {
  if (process.env.NODE_ENV === 'production' && process.env.STORAGE_DRIVER !== 'local') {
    throw new Error(
      'Refusing to use local disk storage in production. Set STORAGE_DRIVER=s3, ' +
        'AWS_S3_BUCKET and HRMS_S3_KMS_KEY_ID. Instance disk has no backup and ' +
        'disappears with the box.',
    );
  }

  return {
    name: 'local',
    root: ROOT,

    async put(key, body, _options = {}) {
      const full = resolve(key);
      await fs.mkdir(path.dirname(full), { recursive: true });
      if (Buffer.isBuffer(body) || typeof body === 'string') {
        await fs.writeFile(full, body);
      } else {
        // A stream.
        const chunks = [];
        for await (const chunk of body) chunks.push(chunk);
        await fs.writeFile(full, Buffer.concat(chunks));
      }
      return { key };
    },

    async getSignedUrl(key, ttlSeconds) {
      const expires = Date.now() + ttlSeconds * 1000;
      const sig = crypto
        .createHmac('sha256', LOCAL_URL_SECRET)
        .update(`${key}|${expires}`)
        .digest('hex');
      const params = new URLSearchParams({ key, expires: String(expires), sig });
      return `/api/v1/hrms/files/local?${params.toString()}`;
    },

    /** Verify a locally signed URL. Used by the dev-only download route. */
    verifySignedUrl({ key, expires, sig }) {
      if (!key || !expires || !sig) return false;
      if (Number(expires) < Date.now()) return false;
      const expected = crypto
        .createHmac('sha256', LOCAL_URL_SECRET)
        .update(`${key}|${expires}`)
        .digest('hex');
      return (
        expected.length === sig.length &&
        crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(sig))
      );
    },

    async getStream(key) {
      return createReadStream(resolve(key));
    },

    async delete(key) {
      await fs.unlink(resolve(key)).catch((err) => {
        // Already gone is success as far as the caller is concerned.
        if (err.code !== 'ENOENT') throw err;
      });
    },

    async exists(key) {
      try {
        await fs.access(resolve(key));
        return true;
      } catch {
        return false;
      }
    },
  };
}
